//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oprema()
        {
            this.StavkaNarudzbenice = new HashSet<StavkaNarudzbenice>();
            this.StavkaOtpremnice = new HashSet<StavkaOtpremnice>();
            this.StavkaPrimke = new HashSet<StavkaPrimke>();
        }
    
        public int OpremaId { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> MinKol { get; set; }
        public Nullable<int> MaxKol { get; set; }
        public Nullable<int> Kol { get; set; }
        public Nullable<float> JedCijena { get; set; }
        public Nullable<int> VrstaOpremeId { get; set; }
    
        public virtual VrstaOpreme VrstaOpreme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaNarudzbenice> StavkaNarudzbenice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaOtpremnice> StavkaOtpremnice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPrimke> StavkaPrimke { get; set; }
    }
}
