//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpremnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otpremnica()
        {
            this.StavkaOtpremnice = new HashSet<StavkaOtpremnice>();
        }
    
        public int OtpremnicaId { get; set; }
        public string AdresaDostave { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<int> ZaposlenikId { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaOtpremnice> StavkaOtpremnice { get; set; }
    }
}
