//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Primka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Primka()
        {
            this.StavkaPrimke = new HashSet<StavkaPrimke>();
        }
    
        public int PrimkaId { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
        public Nullable<int> ZaposlenikId { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPrimke> StavkaPrimke { get; set; }
    }
}
