//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skladistedbEntities : DbContext
    {
        public skladistedbEntities()
            : base("name=skladistedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Narudzbenica> Narudzbenica { get; set; }
        public virtual DbSet<Oprema> Oprema { get; set; }
        public virtual DbSet<Otpremnica> Otpremnica { get; set; }
        public virtual DbSet<Primka> Primka { get; set; }
        public virtual DbSet<StavkaNarudzbenice> StavkaNarudzbenice { get; set; }
        public virtual DbSet<StavkaOtpremnice> StavkaOtpremnice { get; set; }
        public virtual DbSet<StavkaPrimke> StavkaPrimke { get; set; }
        public virtual DbSet<VrstaOpreme> VrstaOpreme { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
