//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladiste
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaNarudzbenice
    {
        public int NarudzbenicaId { get; set; }
        public int OpremaId { get; set; }
        public Nullable<int> Kol { get; set; }
    
        public virtual Narudzbenica Narudzbenica { get; set; }
        public virtual Oprema Oprema { get; set; }
    }
}
